### PR TITLE
Fix for Issue 4

### PR DESCRIPTION
**Pull request by twomice**
As discussed in https://github.com/mattwire/webform_civicrm_esign/issues/4#issuecomment-535578395

### CODE REVIEW

**Comment by twomice** [comment]
Hi @mattwire Any thoughts on the suitability of this PR?

**Comment by mattwire** [comment]
@twomice Yes probably :-)  Ping me next week if I don't get back to you - I hope to have a look during the sprint.

**Comment by twomice** [comment]
Pinging @mattwire . Any update on merge status?

**Comment by twomice** [comment]
Thanks @mattwire !

**Pull request merged**
